spring:
  application:
    name: ms-order
  config:
    import: optional:configserver:http://localhost:8888


  # PostgresSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_order
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Eureka Configuration
  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  # Server Configuration
  server:
    port: 8080

# Swagger Configuration (Optional)
api:
  common:
    version: Local
    title: order service
    description: order service Documentation
    termsOfService: MY TERMS OF SERVICE
    license: license
    licenseUrl: https://inwi.ma/LICENSE-0.0.1.html
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  config:
    products-url: http://localhost:8082/product